### PR TITLE
fix document display

### PR DESCRIPTION
**Pull request by cuishuang**
before:

image

after:

image

### CODE REVIEW

**Comment by Jun10ng** [comment]
thanks

**Comment by Jun10ng** [comment]
> Hi @cuishuang, welcome to mosn community, Please sign [Contributor License Agreement!](http://cla.sofastack.tech/mosn)
> 
> After you signed CLA, we will automatically sync the status of this pull request in 3 minutes.

@cuishuang  hi, you need complete this first.

**Comment by cuishuang** [comment]
> thanks

Done

**Comment by cuishuang** [comment]
> > Hi @cuishuang, welcome to mosn community, Please sign [Contributor License Agreement!](http://cla.sofastack.tech/mosn)
> > After you signed CLA, we will automatically sync the status of this pull request in 3 minutes.
> 
> @cuishuang hi, you need to complete this first.

But in fact, I waited for 3 minutes after signing, and found that the synchronization still did not succeed

**Review by Jun10ng — APPROVED** [review]

**Pull request merged**
