### PR TITLE
fix spelling mistake

### PR DESCRIPTION
**Pull request by wangjc0216**
Readme doc spelling  mistake

### CODE REVIEW

**Comment by cch123** [comment]
> Readme doc spelling mistake

Please sign the CLA, and I'll merge this~

**Comment by wangjc0216** [comment]
> > Readme doc spelling mistake

I have signed the CLA, 曹大~

**Comment by cch123** [comment]
Thanks for contribution~

**Comment by taoyuanyuan** [comment]
@wangjc0216  the `current_goroutine_num` should be 10, and pls fix it too. thank you！
```
holmes.WithGoroutineDump(10, 25, 2000)
```

**Comment by wangjc0216** [comment]
> 

ok,I got the message just now , now I rebuild another pr to fix it 😂  #35

**Pull request merged**
